apiVersion: v1
kind: ServiceAccount
metadata:
  name: llm-guard-sa
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "llm-guard.labels" . | nindent 4 }}
automountServiceAccountToken: false
