apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "agent-sandbox.labels" . | nindent 4 }}
automountServiceAccountToken: false
