{{- if .Values.audit.demoDsn }}
# ☢️ DEMO-ONLY audit DB DSN.
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.audit.databaseSecretName }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  {{ .Values.audit.databaseSecretKey }}: {{ .Values.audit.demoDsn | quote }}
{{- end }}
