{{- range $ns := list "gateway" "platform" "mcp" "sandbox" }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $ns }}
  labels:
    kubernetes.io/metadata.name: {{ $ns }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    linkerd.io/inject: enabled
---
{{- end }}
