image:
  repository: ghcr.io/lee-mcfaul2/pii-tokenizer
  tag: 0.1.0
  pullPolicy: IfNotPresent

replicas: 2

resources:
  requests:
    cpu: 200m
    memory: 128Mi
  limits:
    cpu: 1000m
    memory: 512Mi

kmaster:
  backend: aead-local
  demoKey: ""
  aeadLocal:
    secretName: pii-tokenizer-kmaster
  vault:
    addr: ""
    keyName: pii-tokenizer
  awsKms:
    region: ""
    keyId: ""
  pkcs11:
    lib: ""
    slot: "0"
    label: kmaster

redis:
  mode: single
  addrs: "redis.platform.svc.cluster.local:6379"

initKMaster: true

service:
  port: 8443

namespace: platform
