apiVersion: v1
kind: Service
metadata:
  name: demo-ui
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector: { app: demo-ui }
  ports:
    - { name: http, port: {{ .Values.service.port }}, targetPort: http, nodePort: {{ .Values.service.nodePort }} }
